### ISSUE TITLE
Write a documentation page about setting references (cmd_odom vs. odometry initialization)

### ISSUE THREAD

**Issue by klaxalk** [ctu-mrs/mrs_uav_system#10]

**Comment by matemat13** [comment]
what do you mean by "odometry initialization"?

**Comment by klaxalk** [comment]
When creating a position reference based on the current position. In this case, using the current estimate is not the best idea most of the time.

**Comment by klaxalk** [comment]
And I remember this explaining to pretty much everyone at some point.

**Comment by matemat13** [comment]
several times for some :D

**Comment by matemat13** [comment]
I'll try to write this up.

**Comment by matemat13** [comment]
@klaxalk pls review the page ([https://ctu-mrs.github.io/docs/system/relative_commands.html](https://ctu-mrs.github.io/docs/system/relative_commands.html)) so we can close this issue.

**Comment by klaxalk** [comment]
Thanks a lot! Its beautiful.
