### ISSUE TITLE
Update px4_firmware to 1.12.3.

### ISSUE THREAD

**Issue by klaxalk** [ctu-mrs/mrs_uav_system#119]
* [px4_firmware](https://github.com/ctu-mrs/px4_firmware)
* 1.12.3 was tested in real flight, offboard worked well.
* But we should check first if it brings some downsides.

**Comment by matemat13** [comment]
what kind of checks do you suggest?

**Comment by klaxalk** [comment]
@matemat13 the most issues I can see now is going to be with simulation. It might force us to update the mavlink SITL gazebo again, which might paralyze us for some time.

**Comment by spurnvoj** [comment]
We already updated Firmware to 1.13.2 here https://github.com/ctu-mrs/uav_core/pull/36 and https://github.com/ctu-mrs/simulation/pull/33
