### ISSUE TITLE
Collision avoidance uses gps_origin even when rtk_origin is available.

### ISSUE THREAD

**Issue by klaxalk** [ctu-mrs/mrs_uav_system#120]

**Comment by spurnvoj** [comment]
@klaxalk Is this still the issue?

**Comment by klaxalk** [comment]
Yes, the _mrs_uav_odometry_ provides TFs between UTM_ORIGIN and GPS_ORIGIN based on the normal GPS, even when RTK is present.

**Comment by spurnvoj** [comment]
I expect that @petrlmat already knows about it and has it in TODOs. However, I am still going to assign this issue to him.
