### ISSUE TITLE
On Modeling a new drone

### ISSUE THREAD

**Issue by MicheleBolognini** [ctu-mrs/mrs_uav_system#13]
Hello MRS team,

as I am considering using your MRS UAV system for research in my projects, I need to ask some questions which I think will be helpful to many others too. The most important one being the following:

How can I model a drone that is different from the ones already included among your options?
My approach would be to find the ROS/Gazebo files that describe your drones, copy them in my own workspace and modify them, but I am unable to find them. Are they contained in the _uav_core_ package?
Also, do you suggest a different method?

Thanks
Michele

**Comment by spurnvoj** [comment]
Hi Michele, 
our drones are specified using [xacro](http://wiki.ros.org/xacro) files which make possible to spawn drones with different settings. Our spawning scripts and setting of drones are in package [mrs_simulation](https://github.com/ctu-mrs/mrs_simulation), which is part of the simulation repository of the mrs_uav_system. You will probably find it in `~/mrs_workspace/src/simulation/ros_packages/mrs_simulation/`.
The robots are specified in subfolder [models/mrs_robots_description](https://github.com/ctu-mrs/mrs_simulation/tree/master/models/mrs_robots_description) where are also 3D models of sensors and part of the drones. 

Vojta
