### ISSUE TITLE
On modeling a tether

### ISSUE THREAD

**Issue by MicheleBolognini** [ctu-mrs/mrs_uav_system#14]
Dear MRS team,

supposing I need to simulate the presence of a tether connecting a pair of drones, and given that I only need to simulate its pulling effect on the drones, not necessarily its contact with the environment, what would be the best way to implement this?

I have considered modeling it as a series of segments in gazebo, connected through spherical joints, but the behavior is not satisfying and it severely burdens the computation. I would like to specify the model (series of masses connected through spring and dampers) as a set of differential equations and have them solved during the simulation. My approach would be to write a ROS node that performs this simulation and communicates the result (cable configuration + forces exerted on the drones) to gazebo, so that the pulling forces on the drones are also simulated. Is there a better way to do this in your framework?

Thanks
Michele

**Comment by spurnvoj** [comment]
Hi Michele,
I think the best way will be to create a world plugin, that you will attach to your gazebo world. You can check our package [mrs_gazebo_extras_resources](https://github.com/ctu-mrs/mrs_gazebo_extras_resources) with world plugin [link_attacher](https://github.com/ctu-mrs/mrs_gazebo_extras_resources/blob/master/src/link_attacher.cpp) that is allowing to rigidly attach and detach two objects together and also to apply force on a specific object. So you can use it as the template and adjust it for your purpose.

Vojta
