### ISSUE TITLE
Is there a easy way to implement a simulation environment with mrs?

### ISSUE THREAD

**Issue by zj0042** [ctu-mrs/mrs_uav_system#156]
As a newbie in ROS environment and mrs system, is there a easy way to implement a simulation environment  by using mrs system? I have read the documents and deployed them on my virtual box environment. But still totally messed with this system.
requirement: If I want to use mrs to simulate a drone flying along with a defined path, and write down the control command when the drone is flying.
questions: 
1) do I need to create my own workspace and write some yml documents? I tried examples under the directory mrs_workspace/src/simulation/exmpales... but I can not do well with "catkin build under mrs_workspace"
2) doe this project support Python? is there any examples for python program? If I need to program, Python is better for me.
3) Is there any forum to discuss problems I met? I hope to find support somewhere.

Thank you so much!

**Comment by klaxalk** [comment]
@lidiaxp thanks! I missed this issue. I hope @zj0042 got past the initial learning curve. If not, there is a completely new set of instructions and examples linked from the https://github.com/ctu-mrs/mrs_uav_system README.
