### ISSUE TITLE
🐞 Error installation via stable PPA

### ISSUE THREAD

**Issue by aaraujo11** [ctu-mrs/mrs_uav_system#173]
**Describe the bug**
Error while installing full system, via PPA, the issue seems to be in the package coppelia-simulation, the version CoppeliaSim_Edu_V4_6_0_rev10_Ubuntu20_04 does not exists anymore the[ url is down](https://www.coppeliarobotics.com/files/V4_6_0_rev10/CoppeliaSim_Edu_V4_6_0_rev10_Ubuntu20_04.tar.xz
), maybe it should be modified to the new available version [V4_6_0_rev14_Ubuntu20_04](https://www.coppeliarobotics.com/files/V4_6_0_rev14/CoppeliaSim_Edu_V4_6_0_rev14_Ubuntu20_04.tar.xz).

**Comment by klaxalk** [comment]
Thanks, it is fixed. I will need to find a way to make sure this never breaks outside of our control. ...
