### ISSUE TITLE
URGENT: How to completely remove mrs system full?

### ISSUE THREAD

**Issue by arjungupta72** [ctu-mrs/mrs_uav_system#177]
I had installed mrs uav system using 
`sudo apt install ros-noetic-mrs-uav-system-full`.
I want to completely remove it from my sytem. I tried using the command
`sudo apt remove ros-noetic-mrs-uav-system-full` and `sudo apt purge ros-noetic-mrs-uav-system-full
` but it only remove some files and the ros noetic distribution folder still contains folders and files related to mrs. Please help.
MY system config:
ROS Noetic
Ubuntu 20.04.6 LTS

**Comment by klaxalk** [comment]
https://github.com/ctu-mrs/ppa-stable?tab=readme-ov-file#uninstalling-packages-from-this-ppa

**Comment by arjungupta72** [comment]
> https://github.com/ctu-mrs/ppa-stable?tab=readme-ov-file#uninstalling-packages-from-this-ppa

Thank you
