### ISSUE TITLE
🐞 Installtion error on Ubunto 20.04 ROS Noetic 

### ISSUE THREAD

**Issue by MF-Ahmed** [ctu-mrs/mrs_uav_system#180]
Hi,
 After Adding the stable PPA curl https://ctu-mrs.github.io/ppa-stable/add_ppa.sh | bash
I get the following error after sudo apt install ros-noetic-mrs-uav-system-full

 sudo apt install ros-noetic-mrs-uav-system-full                                                                                                                    
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

Thanks

**Comment by klaxalk** [comment]
> The following information may help to resolve the situation:

missing "The following information that may help to resolve the situation" :-)

**Comment by MF-Ahmed** [comment]
Here is the full message after curl https://ctu-mrs.github.io/ppa-stable/add_ppa.sh | bash
"λ › sudo apt install ros-noetic-mrs-uav-system-full                                                                                            ~
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-noetic-mrs-uav-system-full : Depends: python-is-python3 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
"
Thanks

**Comment by klaxalk** [comment]
It looks like you are missing some important dependencies (-> have you installed ROS ??), or your package manager is in a broken state. The broken state can be sometimes easily fixed with `aptitude`, e.g., by trying
```bash
sudo aptitude install python-is-python3
```

**Comment by MF-Ahmed** [comment]
Thanks, I did "sudo apt install python-is-python3"  and "sudo apt install ros-noetic-mrs-uav-system-full"
The following NEW packages will be installed:
  binutils-dev libio-pty-perl libipc-run-perl libncurses5 libqt5svg5-dev libqt5websockets5-dev libtime-duration-perl libtinfo5 libx264-dev
  moreutils mrs-uav-shell-additions ros-noetic-aloam-slam ros-noetic-catch-ros ros-noetic-ddynamic-reconfigure-python
  ros-noetic-dynamic-edt-3d ros-noetic-mav-msgs ros-noetic-mavlink-sitl-gazebo ros-noetic-mavros-extras ros-noetic-mrs-aloam-core
  ros-noetic-mrs-aloam-estimator-plugin ros-noetic-mrs-bumper ros-noetic-mrs-euler-counter-example ros-noetic-mrs-gazebo-common-resources
  ros-noetic-mrs-hector-core ros-noetic-mrs-hector-estimator-plugin ros-noetic-mrs-lib ros-noetic-mrs-modules-msgs ros-noetic-mrs-msgs
  ros-noetic-mrs-multireconfigure ros-noetic-mrs-multirotor-simulator ros-noetic-mrs-octomap-mapping-planning
  ros-noetic-mrs-octomap-planner ros-noetic-mrs-octomap-server ros-noetic-mrs-octomap-tools ros-noetic-mrs-open-vins-core
  ros-noetic-mrs-open-vins-estimator-plugin ros-noetic-mrs-pcl-tools ros-noetic-mrs-rviz-plugins ros-noetic-mrs-serial
  ros-noetic-mrs-subt-planning-lib ros-noetic-mrs-tf-connector ros-noetic-mrs-tf-estimator ros-noetic-mrs-tf-reconfigure
  ros-noetic-mrs-uav-autostart ros-noetic-mrs-uav-controllers ros-noetic-mrs-uav-coppelia-api ros-noetic-mrs-uav-coppelia-simulation
  ros-noetic-mrs-uav-core ros-noetic-mrs-uav-deployment ros-noetic-mrs-uav-dji-tello-api ros-noetic-mrs-uav-gazebo-simulation
  ros-noetic-mrs-uav-gazebo-testing ros-noetic-mrs-uav-hw-api ros-noetic-mrs-uav-managers ros-noetic-mrs-uav-modules
  ros-noetic-mrs-uav-path-loader ros-noetic-mrs-uav-px4-api ros-noetic-mrs-uav-state-estimators ros-noetic-mrs-uav-status
  ros-noetic-mrs-uav-system-full ros-noetic-mrs-uav-testing ros-noetic-mrs-uav-trackers ros-noetic-mrs-uav-trajectory-generation
  ros-noetic-mrs-uav-trajectory-loader ros-noetic-mrs-utils ros-noetic-mrs-vins-imu-filter ros-noetic-mrs-vins-republisher
  ros-noetic-nimbro-cam-transport ros-noetic-nimbro-log-transport ros-noetic-nimbro-net-monitor ros-noetic-nimbro-network
  ros-noetic-nimbro-service-transport ros-noetic-nimbro-tf-throttle ros-noetic-nimbro-topic-transport ros-noetic-nlopt
  ros-noetic-ouster-ros ros-noetic-ov-core ros-noetic-ov-eval ros-noetic-ov-init ros-noetic-ov-msckf ros-noetic-plotjuggler ros-noetic-px4
  ros-noetic-rviz-satellite ruby-erubis ruby-thor ruby-xdg tmuxinator
The following packages will be upgraded:
  libignition-math6 libignition-math6-dev ros-noetic-rosbag ros-noetic-tf2 ros-noetic-tf2-ros
5 upgraded, 87 newly installed, 0 to remove and 860 not upgraded.
Need to get 162 MB of archives.
After this operation, 263 MB of additional disk space will be used.
W: Sources disagree on hashes for supposely identical version '1.0.14' of 'mrs-uav-shell-additions:amd64'.
Do you want to continue? [Y/n] y
Get:1 http://fr.archive.ubuntu.com/ubuntu focal/universe amd64 libqt5svg5-dev amd64 5.12.8-0ubuntu1 [10.3 kB]
Get:2 http://fr.archive.ubuntu.com/ubuntu focal/main amd64 libio-pty-perl amd64 1:1.12-1 [32.4 kB]                            
Get:3 http://fr.archive.ubuntu.com/ubuntu focal/main amd64 libipc-run-perl all 20180523.0-2 [89.7 kB]
Get:4 http://fr.archive.ubuntu.com/ubuntu focal-updates/universe amd64 libtinfo5 amd64 6.2-0ubuntu2.1 [83.4 kB]
Get:5 http://fr.archive.ubuntu.com/ubuntu focal-updates/universe amd64 libncurses5 amd64 6.2-0ubuntu2.1 [96.9 kB]
Get:6 http://fr.archive.ubuntu.com/ubuntu focal/universe amd64 libqt5websockets5-dev amd64 5.12.8-0ubuntu1 [10.3 kB]
Get:7 http://fr.archive.ubuntu.com/ubuntu focal/universe amd64 libtime-duration-perl all 1.21-1 [13.1 kB]
Get:8 http://fr.archive.ubuntu.com/ubuntu focal/universe amd64 libx264-dev amd64 2:0.155.2917+git0a84d98-2 [569 kB]
Get:9 http://fr.archive.ubuntu.com/ubuntu focal/universe amd64 moreutils amd64 0.63-1 [60.5 kB]
Get:10 http://fr.archive.ubuntu.com/ubuntu focal-updates/main amd64 binutils-dev amd64 2.34-6ubuntu1.8 [3,634 kB]
Get:11 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-msgs 2:1.0.4-0focal.20240129.110426~git.7fbb469 [322 kB]
Get:12 http://fr.archive.ubuntu.com/ubuntu focal/universe amd64 ruby-erubis all 2.7.0-3 [88.6 kB]                 
Get:13 http://fr.archive.ubuntu.com/ubuntu focal/universe amd64 ruby-thor all 0.19.4-1 [43.9 kB]                                   
Get:14 http://fr.archive.ubuntu.com/ubuntu focal/universe amd64 ruby-xdg all 2.2.3-1 [10.2 kB]                                     
Get:15 http://fr.archive.ubuntu.com/ubuntu focal/universe amd64 tmuxinator all 1.1.4-3 [17.5 kB]                                 
Get:16 http://packages.ros.org/ros/ubuntu focal/main amd64 ros-noetic-catch-ros amd64 0.5.0-2focal.20230620.184147 [427 kB]        
Get:17 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-tf2 2:0.7.666-0focal.20230917.065007~git.b496c7d [107 kB]
Get:18 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-lib 2:1.0.4-0focal.20240217.041620~git.5df5318 [345 kB]
Get:19 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-modules-msgs 2:1.0.0-0focal.20240120.041228~git.9b4f67e [120 kB]
Get:20 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-tf2-ros 2:0.7.666-0focal.20230917.065252~git.b496c7d [239 kB]
Get:21 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-ouster-ros 2:0.5.2-0focal.20230917.091947~git.d0ce2c3 [278 kB]
Get:22 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-rosbag 2:1.16.666-0focal.20230917.085426~git.62faf58 [391 kB]
Get:23 http://packages.ros.org/ros/ubuntu focal/main amd64 ros-noetic-ddynamic-reconfigure-python amd64 0.0.1-1focal.20230620.193510 [7,652 B]
Get:24 http://packages.ros.org/ros/ubuntu focal/main amd64 ros-noetic-dynamic-edt-3d amd64 1.9.8-1focal.20220514.014748 [31.5 kB]
Get:25 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-aloam-slam 2:0.0.0-0focal.20240217.042120~git.7a1e842 [244 kB]
Get:26 http://packages.ros.org/ros/ubuntu focal/main amd64 libignition-math6-dev amd64 6.15.1-1~focal [147 kB]
Get:27 http://packages.ros.org/ros/ubuntu focal/main amd64 libignition-math6 amd64 6.15.1-1~focal [111 kB]
Get:28 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mav-msgs 2:3.3.3-0focal.20230917.071626~git.9166311 [48.4 kB]
Get:29 http://packages.ros.org/ros/ubuntu focal/main amd64 ros-noetic-plotjuggler amd64 3.9.0-1focal.20240205.194732 [8,540 kB]
Get:30 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mavlink-sitl-gazebo 2:1.13.2-0focal.20240207.042455~git.40a30ca [671 kB]
Get:31 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mavros-extras 2:1.13.0-0focal.20230917.070658~git.42175c0 [402 kB]
Get:32 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-testing 2:1.0.0-0focal.20240220.090048~on.push.build [138 kB]
Get:33 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-managers 2:1.0.4-0focal.20240219.045906~git.2fe7147 [1,020 kB]
Get:34 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-state-estimators 2:0.0.3-0focal.20240219.051145~git.79362d8 [615 kB]
Get:35 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-aloam-estimator-plugin 2:1.0.0-0focal.20240219.051930~git.c4f9e3b [56.9 kB]
Get:36 http://packages.ros.org/ros/ubuntu focal/main amd64 ros-noetic-rviz-satellite amd64 3.1.0-1focal.20231013.195955 [131 kB]
Get:37 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-aloam-core 2:1.0.0-0focal.20240219.052439~git.6da81a3 [12.6 kB]
Get:38 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-bumper 2:1.0.4-0focal.20240217.043058~git.8a9d81b [233 kB]
Get:39 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-euler-counter-example 2:1.0.0-0focal.20240217.043506~git.700b8b5 [96.3 kB]
Get:40 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-gazebo-common-resources 2:1.0.3-0focal.20240203.041116~git.5ce9745 [47.2 MB]
Get:41 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-hector-estimator-plugin 2:1.0.0-0focal.20240219.052846~git.fe93be3 [57.1 kB]
Get:42 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-hector-core 2:1.0.0-0focal.20240219.053258~git.0fd73ee [11.2 kB]            
Get:43 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-multireconfigure 2:1.0.0-0focal.20231114.203602~git.700b8b5 [5,040 B]       
Get:44 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-hw-api 2:1.0.0-0focal.20240217.052406~git.8ddfa1e [208 kB]              
Get:45 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-multirotor-simulator 2:1.0.0-0focal.20240217.052817~git.7a42cf7 [464 kB]    
Get:46 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-subt-planning-lib 2:0.0.3-0focal.20240217.050735~git.6bf6fc2 [106 kB]       
Get:47 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-octomap-planner 2:1.0.0-0focal.20240217.051246~git.9b33171 [206 kB]         
Get:48 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-octomap-tools 2:1.0.0-0focal.20240217.044016~git.1d35082 [325 kB]           
Get:49 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-octomap-server 2:1.0.0-0focal.20240217.044420~git.d74ed1d [207 kB]          
Get:50 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-octomap-mapping-planning 2:1.0.0-0focal.20240217.051704~git.a417c88 [13.0 kB]
Get:51 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-open-vins-estimator-plugin 2:1.0.0-0focal.20240219.054738~git.7c76b0d [57.1 kB]
Get:52 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-vins-imu-filter 2:0.1.0-0focal.20240217.075911~git.7be6733 [6,556 B]        
Get:53 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-vins-republisher 2:0.0.0-0focal.20240217.080619~git.8e216c6 [73.2 kB]       
Get:54 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-ov-core 2:2.7.0-0focal.20231031.093706~git.22d0666 [549 kB]                     
Get:55 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-ov-eval 2:2.7.0-0focal.20231031.094136~git.22d0666 [336 kB]                     
Get:56 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-ov-init 2:2.7.0-0focal.20231031.094408~git.22d0666 [532 kB]                     
Get:57 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-ov-msckf 2:2.7.0-0focal.20231031.094928~git.22d0666 [1,016 kB]                  
Get:58 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-open-vins-core 2:1.0.0-0focal.20240219.062954~git.1213ed7 [816 kB]          
Get:59 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-pcl-tools 2:1.0.0-0focal.20240217.044856~git.f864fdb [1,224 kB]             
Get:60 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-rviz-plugins 2:1.0.4-0focal.20240217.045647~git.95a4e6b [3,154 kB]          
Get:61 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-serial 2:1.0.0-0focal.20240217.050311~git.2117ec8 [364 kB]                  
Get:62 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-tf-connector 2:1.0.0-0focal.20240217.043549~git.700b8b5 [76.6 kB]           
Get:63 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-tf-estimator 2:1.0.0-0focal.20231114.203716~git.700b8b5 [9,976 B]           
Get:64 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-tf-reconfigure 2:1.0.0-0focal.20240217.043618~git.700b8b5 [105 kB]          
Get:65 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-autostart 2:1.0.4-0focal.20240220.090208~on.push.build [124 kB]         
Get:66 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-controllers 2:1.0.4-0focal.20240219.050544~git.222c551 [466 kB]         
Get:67 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-coppelia-api 2:1.0.0-0focal.20240217.053425~git.ebc395a [91.2 kB]       
Get:68 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-coppelia-simulation 2:1.0.0-0focal.20240217.053505~git.ebc395a [236 kB] 
Get:69 https://ctu-mrs.github.io/ppa-stable ./ mrs-uav-shell-additions 1.0.14 [5,160 B]                                                     
Get:70 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-status 2:1.0.4-0focal.20240217.055332~git.e978494 [208 kB]              
Get:71 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-trackers 2:1.0.4-0focal.20240220.085709~on.push.build [618 kB]          
Get:72 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-nlopt 2:2.4.2-0focal.20231010.202347~git.3e71681 [226 kB]                       
Get:73 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-trajectory-generation 2:1.0.4-0focal.20240220.090601~on.push.build [438 kB]
Get:74 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-core 2:1.0.0-0focal.20240219.060505~git.df7a857 [10.7 kB]               
Get:75 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-deployment 2:1.0.0-0focal.20240210.042821~git.5088bfe [455 kB]          
Get:76 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-dji-tello-api 2:1.0.0-0focal.20240217.053916~git.13316a9 [125 kB]       
Err:77 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-gazebo-testing 2:1.0.0-0focal.20240220.044614~git.43ae3ff               
  404  Not Found [IP: 185.199.110.153 443]
Get:78 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-px4-api 2:1.0.0-0focal.20240217.054846~git.fccf071 [149 kB]             
Get:79 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-px4 1.13.2 [76.5 MB]                                                            
Get:80 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-gazebo-simulation 2:1.0.3-0focal.20240220.045020~git.2a9cc52 [4,929 kB] 
Get:81 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-path-loader 2:1.0.0-0focal.20240217.054334~git.1b3d5a3 [47.7 kB]        
Get:82 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-trajectory-loader 2:1.0.0-0focal.20240217.074554~git.b44be4e [80.3 kB]  
Get:83 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-utils 2:1.0.0-0focal.20240217.043701~git.700b8b5 [4,784 B]                  
Get:84 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-nimbro-cam-transport 2:0.0.1-0focal.20231011.202929~git.b73ea32 [44.6 kB]       
Get:85 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-nimbro-log-transport 2:1.0.0-0focal.20231011.202957~git.b73ea32 [63.0 kB]       
Get:86 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-nimbro-net-monitor 2:0.0.1-0focal.20231011.203045~git.b73ea32 [70.1 kB]         
Get:87 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-nimbro-service-transport 2:1.0.0-0focal.20231011.203127~git.b73ea32 [139 kB]    
Get:88 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-nimbro-tf-throttle 2:1.0.0-0focal.20231011.203221~git.b73ea32 [33.0 kB]         
Get:89 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-nimbro-topic-transport 2:1.0.0-0focal.20231011.203259~git.b73ea32 [185 kB]      
Get:90 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-nimbro-network 2:2.0.0-0focal.20231011.203417~git.b73ea32 [4,740 B]             
Get:91 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-modules 2:1.0.0-0focal.20240217.075213~git.0f86b48 [4,848 B]            
Get:92 https://ctu-mrs.github.io/ppa-unstable ./ ros-noetic-mrs-uav-system-full 2:1.0.0-0focal.20240220.044212~git.8c210b4 [2,056 B]        
Fetched 162 MB in 18s (9,046 kB/s)                                                                                                          
E: Failed to fetch https://ctu-mrs.github.io/ppa-unstable/./ros-noetic-mrs-uav-gazebo-testing_1.0.0-0focal.20240220.044614~git.43ae3ff_amd64.deb  404  Not Found [IP: 185.199.110.153 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
λ › roscd mrs_uav_gazebo_simulation/tmux/one_drone                                                                                         ~
roscd: No such package 'mrs_uav_gazebo_simulation/tmux/one_drone'

even after sourcing the noetic workspace I'm not able to roscd into mrs_uav_gazebo_simulation

**Comment by klaxalk** [comment]
Hey, to resolve the `404 Not Found [IP: 185.199.110.153 443]` error, do `sudo update update`.

**Comment by klaxalk** [comment]
You can run ORB-SLAM2, that is for sure. I recommend starting with one of our drones presets from the `mrs_uav_gazebo_simulation`. Learn how to spawn them with different sensors (https://ctu-mrs.github.io/docs/simulation/gazebo/gazebo/drone_spawner.html) and find the ones that suit you. If you insist on a custom drone with custom sensor placement, follow the tutorial on how to create your custom drone package: https://ctu-mrs.github.io/docs/simulation/gazebo/gazebo/custom_drone.html.

The MRS system currently contains only one mapping & planning pipeline, the https://github.com/ctu-mrs/mrs_octomap_mapping_planning. However, you can connect other planning pipelines to the system using whatever output comes from the planning pipeline. The system accepts `path`, `trajectory`, or a `single point reference` as an input, so pretty much anything can be done (supposing the reference you generate is transformable by the TF library).

SLAM is only a technique to obtain localization. We integrate and use 4 different SLAMs/Odometries (ALOAM, LIOSAM, Hector, and OpenVins). You could possibly substitute the OpenVins with ORBSLam if you need to. However, to do frontier exploration, you need some volumetric mapping framework (like our [Octomap](https://github.com/ctu-mrs/mrs_octomap_mapping_planning)).

**Comment by MF-Ahmed** [comment]
Thank you very much
