### ISSUE TITLE
px4 compilation fails

### ISSUE THREAD

**Issue by pritzvac** [ctu-mrs/mrs_uav_system#19]
I updated the system and the compilation of px4 fails with the following error:
```
Errors     << px4:make /home/vasek/mrs_workspace/logs/px4/build.make.001.log
make[2]: *** [uORB/topics/uORBTopics.hpp] Error 1
make[1]: *** [msg/CMakeFiles/uorb_headers.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```
Do you have an idea how to fix this?

![Selection_123](https://user-images.githubusercontent.com/23398310/97984999-dd207c80-1dd7-11eb-956c-a8e3c28fbbb7.png)

**Comment by klaxalk** [comment]
We upgraded to a newer version of px4 (1.11.1) which has some new dependencies. Please run the `install.sh` within the [https://github.com/ctu-mrs/simulation](https://github.com/ctu-mrs/simulation) package to update the dependencies and then recompile.
