### ISSUE TITLE
Question about using RTK

### ISSUE THREAD

**Issue by maxhofidrone** [ctu-mrs/mrs_uav_system#34]
Hi,
I want to use the MRS system with a X500 UAV with RTK. As a RTK board I have the [SparkFun GPS-RTK-SMA Breakout board](https://www.sparkfun.com/products/16481) based on the Ublox F9P receiver. As far as I understand, this board will work with the "normal" [PX4 RTK approach](https://docs.px4.io/master/en/gps_compass/rtk_gps.html) (e.g. one base station (RTCM)->QGC->Pixhawk->rover->(Position)->Pixhawk).
I couldn't find the PX4/mavros RTK topic name which is subscribed by the MRS system nor any related options/configs for the RTK input. 

Can I specify the RTK input topic name somewhere if I choose the RTK estimator in the MRS system?

This would be very helpful, as I am later planning to use some online correction service instead an own base station and the RTK rover board would only be connected to the onboard computer and not the Pixhawk [(example)](https://github.com/ajbfinesc/rtkrcv_ros).

Thank you very much in advance!
Max

PS: It was a nice Christmas present to see that you already included the X500. Thanks a lot for this!

**Comment by DanHert** [comment]
Hello, so we use the RTK a bit different, in all our applications, we have the radio receiver for RTK corrections connected straight to the RTK board, and the RTK board then sends the RTK position to the main computer, avoiding the Pixhawk completely.  Our odometry node then subscribes the RTK messages (topic rtk_gps/global), which are used in the estimator.

We have not tried pushing the corrections through pixhawk, or getting the RTK position back from pixhawk, but it is definetly possible. 

Dan H.

**Comment by maxhofidrone** [comment]
Hi @DanHert,
thanks for the clarification. So basically, I could  have any source of a RTK solution (own processing, Pixhawk...) and just need to assure, that I publish this solution to rtk_gps/global. the mrs_uav_odometry package will accept it as valid input then?

Best regards,

Max

**Comment by DanHert** [comment]
Yes, that is correct. 

Cheers, Dan H.

**Comment by maxhofidrone** [comment]
I now successfully set up a ublox F9P with a NTRIP correction service [(source)](https://github.com/ros-agriculture/ublox_f9p). According your last reply, I am now planing to write a simple publisher like [`void RtkRepublisher::callbackTersus(const mrs_msgs::BestposConstPtr &msg)`](https://github.com/ctu-mrs/mrs_uav_odometry/blob/4c58a3b8a4ff61ecccf199e3e52f5098ddea6580/src/rtk_republisher.cpp#L188) to publish the [mrs_msgs/RtkGps.msg](https://ctu-mrs.github.io/mrs_msgs/msg/RtkGps.html). As I understand it based on the `RtkRepublisher::callbackTersus`, I don't need to provide the twist and pose within my RTK solution (which I don't have as it is a RTK only solution...). So I am wondering, what  the original purpose of these twist/pose message parts you are using in [
void RtkRepublisher::timerMain(const ros::TimerEvent &event)](https://github.com/ctu-mrs/mrs_uav_odometry/blob/4c58a3b8a4ff61ecccf199e3e52f5098ddea6580/src/rtk_republisher.cpp#L306) is? Is it only when "simulating" RTK in Gazebo or does it have any further use in `mrs_odometry`?

Cheers,

Max

**Comment by DanHert** [comment]
Hi, you do not need to provide the twist and pose, lat and lon is enough. The twist and pose is intended to be used with UTM coordinates, so if you for some reason have the UTM instead of lat and lon, just fill out the frame id as UTM and use the pose and twist (some GPS/RTK receivers will give you position and speed, so that is the reason for the twist, also the quaternion in pose is not used at all).

And yes, the timerMain is only for simulation, it can also do random jumps in the RTK position (this can happen with the real RTK if you change from RTK Float to RTK Fix for example). So it is for testing failures of the RTK.

Dan H.

**Comment by maxhofidrone** [comment]
ok. 
Thank you very much for the help and clarification!

**Comment by maxhofidrone** [comment]
Hello,
I integrated RTK within ROS and MRS with my custom publisher to /uav1/rtk_gps/global.
For actually using it I still have one question:
Where are the lever arms defined in MRS? (@DanHert  you mentioned the Z-Offset in https://github.com/ctu-mrs/mrs_uav_system/issues/43#issuecomment-784312605)
Or do I need to correct for the lever arms befor sending the positions to the MRS odometry fusion? 

And just for clarification: I can use the RTK state estimation by just setting the `lateral_estimator` to `RTK` right?

Thanks for any help in advance!

**Comment by klaxalk** [comment]
Hey, before flying, pull the `uav_core`. We have had a bad remapping of the RTK topic into the `rtk_republisher` node's [launch]().

**Comment by maxhofidrone** [comment]
Hi,
I will do, but I don't understand why the `rtk_republisher` is relevant here for me? I am not using the Tersus RTK. I am using a ublox F9P and publishing its solution already to  `rtk_gps/global`. My question concerns how to apply the lever arm of the RTK. Is it done inside MRS or should I correct it before publishing it to MRS.

**Comment by DanHert** [comment]
Hi, yeah you do not need the `rtk_republisher`. The lever arm is not handled at all by the system, so if you want to be as precise as possible, you need to correct it yourself.

Dan H.
