### ISSUE TITLE
Problem running the Optical Flow example scripts 

### ISSUE THREAD

**Issue by lkova** [ctu-mrs/mrs_uav_system#41]
I am unable to takeoff with a drone in any example that uses optical flow as a primary sensor. The problem is that odometry is not initialized and the optical flow velocity is not published.

The following is the terminal output from the script example_tmux_scripts/one_drone_optic_flow, but it happens with other optical flow examples as well.

![one_drone_optic_flow](https://user-images.githubusercontent.com/6342730/107760462-113a0080-6d2a-11eb-963e-225cf0041313.png)

What can be the problem with this and how can I solve it?

Thanks!

**Comment by DanHert** [comment]
Hello!
Did you actually clone and compile the optic flow repository? - https://github.com/ctu-mrs/mrs_optic_flow
It will not be cloned by the default install script.

So clone the optic flow repository, run the install script from the install folder, link it to you workspace and compile.

Dan H.

**Comment by lkova** [comment]
Thanks!
That was the solution to my problem.

Btw, thanks for sharing this with the community, it has been of great help.

Luka
