### ISSUE TITLE
Using the software to simulate fully actuated hexarotor dynamics

### ISSUE THREAD

**Issue by kefran88** [ctu-mrs/mrs_uav_system#45]
Hello CTU team,

I have been using your software for a while and I would like to use it to study the dynamics of fully actuated hexarotor. 
I have noticed that in the models there is already an hexarotor f550, but to make it fully actuated, I need to be able to tilt the rotors. Is it possible to do it directly in the xacro file ? Or do I need some extra files and build another xacro file ? 
 
Best regards,

Frank

**Comment by DanHert** [comment]
Hello, you can just modify the .xacros to tilt the rotors:
![image](https://user-images.githubusercontent.com/20679389/109483903-10ba9d00-7a80-11eb-8837-ab794a92ced4.png)

But we use PX4 as a low level controller, and to my knowledge it does not support fully actuated platforms. But you can maybe try something like this - https://github.com/castacks/PX4-fully-actuated

Cheers, Dan H.

**Comment by WingRS** [comment]
Hi @kefran88,
Since Dan has answered your question (looks crazy if you ask me), I am closing the issue, if you have more questions - feel free.
