### ISSUE TITLE
RTK offset 

### ISSUE THREAD

**Issue by ZakariaLaakel** [ctu-mrs/mrs_uav_system#63]
Hello MRS Team,

As explained in #54, I added an offset in the [odometry.cpp](https://github.com/ctu-mrs/mrs_uav_odometry/blob/master/src/odometry.cpp#L4245) file to have relevant Z position when using the RTK as altitude estimator. By default, with no offset, the Z-component decreases linearly until -66.76, where it is then steady. By adding  a counter offset this line of code is in our case 

`odom_main.pose.pose.position.z = alt_x(mrs_msgs::AltitudeStateNames::HEIGHT) + 66.76 ;`

This allows to have a value of 0.25m for the z component when it is on the ground (which is what we want in the end).
There are 2 different problems when applying this solution:

- This offset is not exactly -66.76m. Depending on the flight zone it is -66m or -67m, so it requires us to constantly change this offset value in the source file.
- Since we want our code to be perfectly working with your latest software this means that the modification above will always be deleted when we pull your latest commits.

Is there a way to fix this issue? Did you already encounter it? We thought as a solution to add a parameter in the odometry yaml file such that
`odom_main.pose.pose.position.z = alt_x(mrs_msgs::AltitudeStateNames::HEIGHT) + offset_rtk_z ;`

 Is it possible to create a parameter `offset_rtk_z ` the same way you defined [(those)](https://github.com/ctu-mrs/mrs_uav_odometry/blob/7a426514ae410610be6ad5988b3738f918f06ea4/src/odometry.cpp#L1216)such that I can use it in odometry.cpp ?

This way I can stay up-to-date and  keep working with my custom_configs, without changing the src files. 

Best, 

Zakaria

**Comment by petrlmat** [comment]
Hi, this offset depends on the ASL altitude of your location. It is estimated during the intialization of the RTK estimator. There was a small bug in the initialization, which should be fixed in https://github.com/ctu-mrs/mrs_uav_odometry/commit/34d5922563a0640447fcad2da32af05b2c6825e0. I cannot test it on real hardware right now, but now the altitude is correct on rosbag data. 

Let me know, if it works for you. Thanks!

**Comment by ZakariaLaakel** [comment]
Hey @petrlmat,

The RTK Z coordinates gives by default 0.2m now, which is indeed the height of our RTK device relative to the ground.
Thank you very much for your help !
