### ISSUE TITLE
Communicating UAV position using Nimbro

### ISSUE THREAD

**Issue by Chelsea-NGolo** [ctu-mrs/mrs_uav_system#72]
Hi,

I had questions concerning the usage of the nimbro network. I followed the explanations found on [https://github.com/ctu-mrs/nimbro_network/blob/master/nimbro_topic_transport/doc/getting_started.md ](url) and was able to reproduce the example successfully.

I am doing experiments with several drones and in order to avoid collisions I want to transmit a custom topic that contains information regarding the position of the drones. I added the name of the topics in the topics.yaml file of the nimbro_network folder for the tcp receiver and sender but when I send the topic I can only send a default topic through the command:

`rostopic pub -r 1.0 /uav1/control_manager/custom_tracker/custom_msgs msgs "{x: 0.0, y: 0.0, z: 0.0, heading: 0.0}"`

How can I tweak this if I want to send the real position of the drone in a simulation (and in during real experiments) and not only "x: 0.0, y: 0.0, z: 0.0, heading: 0.0"?.

How should I proceed if I want to perform real life experiments with several drones. I have a folder with simulations and tmux scripts for real life experiments. Should I run the .sh script of this experiment on each computer of the drones or should I launch it once and then ssh in all the different computers?

KR,

N'Golo

**Comment by klaxalk** [comment]
Hey, making Nimbro run correctly on real hardware is one of the tougher tasks, but it can be done :-).

1. follow the instructions in the main README.md in [https://github.com/ctu-mrs/nimbro_network](https://github.com/ctu-mrs/nimbro_network)
2. run the **install.sh** in there (part of the instructions)
3. check our main Nimbro launch file here [https://github.com/ctu-mrs/mrs_uav_general/blob/master/launch/nimbro.launch](https://github.com/ctu-mrs/mrs_uav_general/blob/master/launch/nimbro.launch)
4. this Nimbro launch file loads a [config file](https://github.com/ctu-mrs/mrs_uav_general/blob/master/config/uav_names.yaml) with the hostnames of all the computers that are going to be connected together, and another [config file](https://github.com/ctu-mrs/mrs_uav_general/blob/master/config/communication_config.yaml) with the list of enabled topics and services.
5. the communication can work only if your UAVs can ping each other using their hostnames (listed in the config file), therefore, make sure you have your `/etc/hosts` configured properly (we have a [script](https://github.com/ctu-mrs/uav_core/blob/master/miscellaneous/dotssh/generate_ssh_config.sh) for that as well).

When you have this ready, you can share topics across the UAVs. Sending of real data can be of course done by publishing the data using a ROS node. In the case of our system, you can, for example, get the current position of the UAV by subscribing to some of the `/uav*/odometry/` topics, check the [ROS interface](https://ctu-mrs.github.io/docs/system/uav_ros_interface.html) to our system.
