### ISSUE TITLE
Installation procedure get stuck with google-guest-agent service on Ubuntu 18.04🐞 

### ISSUE THREAD

**Issue by gsilano** [ctu-mrs/mrs_uav_system#75]
Running the automatic installation procedure on Ubuntu 18.04 over an existing release of the MRS system (for the case of interest that was that in October 2020), the system gets stuck with the `google-gust-agent` service and the installation fails. Whether trying to remove the service by using `sudo dpkg` command or the `sudo apt remove` command there is no way to fix it. The installation procedure still fails. This appears to be due to a service restarting each time is interrupted. Then, the installation stops by raising locks on any other command (e.g., `sudo apt update` or `sudo apt upgrade`). @bednarhonza can tell more about this.

Eventually, @ViktorWalter solved the issue by running `sudo htop` and killing the service and its related dependencies when it got stuck. Of course, this can be considered only as a temporary fix. Students or even me could have trouble in case a system update is required. 

Below are listed the services we stopped to make it work.

```
sudo systemctl stop google-guest-agent.service google-shutdown-scripts.service google-startup-scripts.service 
```

**Comment by spurnvoj** [comment]
This service should no be installed anymore, so new students will not have
this problem.

st 12. 5. 2021 v 23:10 odesílatel Giuseppe Silano ***@***.***>
napsal:
