### ISSUE TITLE
RTK settings

### ISSUE THREAD

**Issue by RaphaelNetels** [ctu-mrs/mrs_uav_system#77]
Hello MRS,

I am still struggling to use the RTK correctly for the real hardware. I want to increase the rate at which position data is sent to the controller (from 1Hz to 10 Hz) but I am not sure what to change. I tried changing the GNSS update rate to 10 Hz but it does not seem to change anything. In the figures, the settings of the base (reach emlid RS2) and the rover (reach emlid M2) can be seen. Is there something I did not correctly or that can be improved?

Base settings:
![base_BaseMode](https://user-images.githubusercontent.com/69520322/118132813-67d5da00-b400-11eb-9f05-cbcd003f6746.png)
![base_PositionOuput](https://user-images.githubusercontent.com/69520322/118132814-686e7080-b400-11eb-8fe6-4b1e9b0c1c91.png)
![base_CorrectionInput](https://user-images.githubusercontent.com/69520322/118132817-69070700-b400-11eb-92d3-e5d5b864a577.png)
![base_RTKsettings](https://user-images.githubusercontent.com/69520322/118132819-69070700-b400-11eb-8a76-121ebc593865.png)

Rover settings:
![rover_BaseMode](https://user-images.githubusercontent.com/69520322/118132925-83d97b80-b400-11eb-8090-c6278eb0d52e.png)
![rover_CorrectionOutput](https://user-images.githubusercontent.com/69520322/118132927-84721200-b400-11eb-80f0-77207fc4504a.png)
![rover_CorrectionInput](https://user-images.githubusercontent.com/69520322/118132935-850aa880-b400-11eb-9457-d63ea1e35fd1.png)
![rover_RTKsettings](https://user-images.githubusercontent.com/69520322/118132936-850aa880-b400-11eb-9f4b-90330172c582.png)

Thank you for your response and time!

Best
Raphaël

**Comment by DanHert** [comment]
![118132927-84721200-b400-11eb-80f0-77207fc4504a](https://user-images.githubusercontent.com/20679389/118134175-e97a3780-b401-11eb-9963-fe62c2914dfa.png)

Change this to 10 Hz

Dan H.

**Comment by RaphaelNetels** [comment]
Thank you!

Raphaël
