### ISSUE TITLE
An error occurred after fresh instalation. missing Geoid Model dataset

### ISSUE THREAD

**Issue by Maderator** [ctu-mrs/mrs_uav_system#8]
After installing fresh Ubuntu 18.04 I ran both scripts in README in order to install mrs_uav_system and Kalaxalk's Linux environment. Right after that, I ran script `~/mrs_workspace/src/simulation/example_tmux_scripts/one_drone_gps/start.sh`

There was an error while spawning drone:
`[FATAL] [1590844627.933957448]: UAS: GeographicLib exception: File not readable /usr/share/GeographicLib/geoids/egm96-5.pgm | Run install_geographiclib_dataset.sh script in order to install Geoid Model dataset!`
and
...`=======REQUIRED process [uav1/mavros-2] has died!`

So I had to run a script `~/mrs_workspace/src/uav_core/ros_packages/mavros/mavros/scripts/install_geographiclib_datasets.sh` in order to get rid of the error.

Was there an error only in my case of installing the mrs_uav_system or is the script `install_geographiclib_datasets.sh` missing in the installation?

**Comment by klaxalk** [comment]
Yes, thanks! I added it into the `install.sh` of the **uav_core** repository.
