### ISSUE TITLE
Compilation error workspace

### ISSUE THREAD

**Issue by RaphaelNetels** [ctu-mrs/mrs_uav_system#80]
Dear MRS team

I was trying to build my workspace with my controllers and trackers but I got the following error. It looks to me that something is not declared correctly. My trackers and controllers are based on the SE3controller that is why I went through all the commits you did but could not solve the problem. Do you have any idea what it could be?

![Screenshot from 2021-06-17 10-04-45](https://user-images.githubusercontent.com/69520322/122356860-7cebde80-cf53-11eb-9a20-dff2c7fa972d.png)

Thank you in advance for your response!
Best regards
Raphaël

**Comment by klaxalk** [comment]
Hey, really hard to say. This does not look like our code. Without seeing the code, I can't help.
