### ISSUE TITLE
mrs_uav_system for NXP hovergame drones

### ISSUE THREAD

**Issue by y2d2** [ctu-mrs/mrs_uav_system#87]
Hi,
Not sure if this is an actual issue. So I apologize if this is not the correct place to ask this. 

I'm currently looking into using your wonderful framework on a  [NXP hovergame drone](https://www.nxp.com/design/designs/nxp-hovergames-drone-kit-including-rddrone-fmuk66-and-peripherals:KIT-HGDRONEK66)  which has the PX4 flight controller. 

I'm trying to understand how much work it would  need to get the mrs_uav_system running on this drone ? And what are the potential pitfalls when trying to do so? How much fine-tuning is needed to make it fly stable ? 

Dependable on the effort we might stick to the drones you have preconfigured. 

I thank you in advance for your insights, 
Cheers, 
Y2D2

**Comment by klaxalk** [comment]
Hey, if the kit offers PixHawk, it should work just fine. You will also need to:
- obtain a companion computer, we recommend the Intel NUC,
- obtain motor thrust parameters by measuring at least two pairs of values "[throttle, UAV mass]". This can be later fed into a script to obtain the thrust parameters.

Fine-tuning might not be necessary, this frame will behave very similarly to the DJI F450.
