### ISSUE TITLE
MRS UAV System Ubuntu 18.04 ROS Melodic - Build Status failing 

### ISSUE THREAD

**Issue by JonathanVogt** [ctu-mrs/mrs_uav_system#88]
Hello,

I need to install the MRS UAV System on Ubuntu 18.04 with ROS Melodic but as you can see on the README, the Build Status is failing. Here is the error I get:

![Screenshot from 2021-07-08 14-01-09](https://user-images.githubusercontent.com/83419926/124918109-f4fa7100-dff4-11eb-8d09-e90ea7f9cb7b.png)

Have you planned to fix it ?

**Comment by klaxalk** [comment]
Hey, sorry, there was a brief moment when the gitman installation was broken. Try it now. But pull the **mrs_uav_system** first.
