### ISSUE TITLE
🐞 MRS UAV failing installation on POP!_OS 21.04

### ISSUE THREAD

**Issue by Scytheroid** [ctu-mrs/mrs_uav_system#94]
Hi,

I would like to install MRS UAV on POP OS, but I keep getting this error:

`
adolf@pop-os:/tmp$ cd /tmp
echo '
GIT_PATH=~/git
mkdir -p $GIT_PATH
cd $GIT_PATH
sudo apt-get -y install git
git clone https://github.com/ctu-mrs/mrs_uav_system
cd mrs_uav_system
git checkout master
git pull
./install.sh -g $GIT_PATH
source ~/.bashrc' > clone.sh && source clone.sh
[sudo] password for adolf: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.30.2-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
fatal: destination path 'mrs_uav_system' already exists and is not an empty directory.
Already on 'master'
Your branch is up to date with 'origin/master'.
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
bc is already the newest version (1.07.1-2build2).
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
/home/adolf/git/mrs_uav_system/dependencies/ros.sh: Installing ROS
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gnupg is already the newest version (2.2.20-1ubuntu3).
lsb-release is already the newest version (11.1.0ubuntu2).
wget is already the newest version (1.21-1ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
--2021-07-21 11:51:16--  http://packages.osrfoundation.org/gazebo.key
Resolving packages.osrfoundation.org (packages.osrfoundation.org)... Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
52.52.171.73
Connecting to packages.osrfoundation.org (packages.osrfoundation.org)|52.52.171.73|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1772 (1.7K) [application/octet-stream]
Saving to: ‘STDOUT’

-                100%[========>]   1.73K  --.-KB/s    in 0s      

2021-07-21 11:51:16 (3.85 MB/s) - written to stdout [1772/1772]

OK
Hit:1 http://ppa.launchpad.net/system76/pop/ubuntu hirsute InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu hirsute InRelease      
Get:3 http://us.archive.ubuntu.com/ubuntu hirsute-security InRelease [101 kB]
Ign:4 http://packages.osrfoundation.org/gazebo/ubuntu-stable hirsute InRelease
Hit:5 http://apt.pop-os.org/proprietary hirsute InRelease        
Err:6 http://packages.osrfoundation.org/gazebo/ubuntu-stable hirsute Release
  404  Not Found [IP: 52.52.171.73 80]
Get:7 http://us.archive.ubuntu.com/ubuntu hirsute-updates InRelease [109 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu hirsute-backports InRelease [101 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu hirsute-security/main amd64 c-n-f Metadata [3,196 B]
Get:10 http://us.archive.ubuntu.com/ubuntu hirsute-updates/main amd64 Packages [279 kB]
Get:11 http://us.archive.ubuntu.com/ubuntu hirsute-updates/universe i386 Packages [217 kB]
Get:12 http://us.archive.ubuntu.com/ubuntu hirsute-updates/universe amd64 Packages [260 kB]
Get:13 http://us.archive.ubuntu.com/ubuntu hirsute-backports/universe amd64 DEP-11 Metadata [9,144 B]
Reading package lists... Done                                    
E: The repository 'http://packages.osrfoundation.org/gazebo/ubuntu-stable hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
/home/adolf/git/mrs_uav_system/dependencies/ros.sh: "sudo apt-get -y update" command failed with exit code 100
./install.sh: "bash $MY_PATH/dependencies/ros.sh" command failed with exit code 100
`

Is this a bug? Is it somehow connected to this issue? 
https://github.com/ctu-mrs/mrs_uav_system/issues/88#issue-939785722

Thanks for response,
Bohdan Kopčák

**Comment by spurnvoj** [comment]
Hi, as the [README](https://github.com/ctu-mrs/mrs_uav_system#build-status) points out, we rely on Ubuntu 18.04 or 20.04. Other systems are not tested, and our system will probably not work for them. 

Vojta
